version: 1
disable_existing_loggers: false

formatters:
  std:
    format: "%(asctime)s %(levelname).1s %(name)s:%(lineno)d â€” %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: std
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]

loggers:
  focus_validator.main:
    level: DEBUG
    propagate: true
  focus_validator:
    level: DEBUG
    propagate: true
  focus_validator.rules.spec_rules.SpecRules:
    level: DEBUG
    propagate: true
  focus_validator.config_objects.rule_dependency_resolver.RuleDependencyResolver:
    level: DEBUG
    propagate: true
  focus_validator.config_objects.rule_dependency_resolver:
    level: INFO
    propagate: true
  validation_results_visualizer:
    level: INFO
    propagate: true
